ALTER TABLE assets ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE certificates ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE applications ADD COLUMN entity_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE people ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE locations ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
